name: Building app
run-name: ${{ github.actor }} is trying to build
on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
jobs:
  my_job:
    name: Running CI
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm ci
        run: npm ci