name: Adding linter Check
run-name: ${{ github.actor }} is trying to run linter
on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install, run linter
        run: |
          npm install
          npm run linter
