name: Adding linter Check
run-name: ${{ github.actor }} Running audit
on: 
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
  schedule:
    - cron: "0 23 * * *"
jobs:
  my_job:
    name: Checking Vunrabilites
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm audit 
        run: |
          npm audit
